language: python
python:
  - "2.7"
# command to instddall dependencies
#install: "pip install -r requirements.txt"
# command to run tests
#script: nosetests
before_script:
  - pep8 --exclude=migrations --ignore=E501,E225 redongo
  - pyflakes -x W redongo
