language: python
python:
- '2.7'
services:
- mongodb
- redis-server
install:
- python setup.py install
- pip install pep8
- pip install pyflakes
- pip install -r requirements.txt
before_script:
- mongo mydb_test --eval 'db.addUser("test", "test123");'
script:
- py.test
notifications:
  slack: stoneworksolutions:dWSagzBbTkOZUk7sZLNSs1AD
deploy:
  provider: pypi
  user: stoneworksolutions
  password:
    secure: htb3biyqy1WwIBVXAwNnGHb8PAqO+esb9D6eiBPxuc8Uk4avcHWXWy3PP2FKgjqgRaniYj9i90JTfQKgbwMLkO5unzE1CRv3XQoZDy1xXhRvxTqnEJGGFhPB+2lID7hj2oZ3wzPYF3fIndw2VxGLO6Qoj0K/U+LcF9gO/UGTv2+teUCdA3I93AiLIa0sXhxWbLror3PL7a+tnGJLBGjkvef8d+Gq6cpiH+ZGbdwyyk5S5uyINOgRarV7vWommYWyvjcBzGlym5eFd38dQRFYB2i18mLltvWK/pjwPphp91teGaZhfDVEwejIdWneJAI0kVLTRuuWwfogGQzW0CWe7bWvyJRTPBX/Fm52sfY9VzPAQdkbFOYN4hxZf8G3FVP7JReT+W970xKRAS7kTGMKgn+5F1XTQQTT9yXLFUSav6DdPM7IF3Zuxr1z7TQe010LlTk1y6mpscNutke/V02P/MCcCXmVHFiUGHKUA8GHWmJilwThotTZBAyRJhO97j3vdYp7O5smGF+iLomtE1qXc8/LIW3Qy46cm7npxEB0SiAJwNn8xPfSigSn+1UE3SMj3cJAOkh42ieMJBljhxeGaypbXRzcaAu83YbYQ4Dg6XaTWmJeEpATpWVejCrn0leQjx38ZjaCp3dwIhf4bh3KirkaV9G6KekZCqGejlZ3Lxs=
  on:
    tags: true
    repo: stoneworksolutions/redongo
