language: python
python:
  - "2.7"
install: 
  - pip install pep8
  - pip install pyflakes
# command to run tests
#script: nosetests
before_script:
  - pep8 --exclude=migrations --ignore=E501,E225,E226 redongo
  - pyflakes redongo
