language: python
python:
  - "2.7"
services:
  - mongodb
  - redis-server
install: 
  - python setup.py install
  - pip install pep8
  - pip install pyflakes
before_script:
  - pip install -r requirements.txt
  - pep8 --exclude=migrations --ignore=E501,E225,E226 redongo
  - pyflakes redongo
before_script:
  - mongo mydb_test --eval 'db.addUser("test", "test123");'

script:
  - py.test
